import mongoose, { Schema } from 'mongoose';

const SavedWordSchema = new Schema(
  {
    userId: { type: String, required: true }, // Reference to the User ID (e.g. from Supabase/Auth)
    word: { type: String, required: true },
    originalSentence: { type: String, required: true },
    meaning: { type: String, required: true }, // Context-aware meaning generated by AI
    example: { type: String }, // Optional usage example generated by AI
    // We can store the full API response snapshot if really needed later, but sticking to requirements for now
  },
  { timestamps: true }
);

// Helper to get model on specific DB ("chat-app")
export function getSavedWordModel() {
  if (mongoose.connection.readyState !== 1) {
    throw new Error('Database not connected');
  }
  const db = mongoose.connection.useDb('chat-app');
  return db.models.SavedWord || db.model('SavedWord', SavedWordSchema);
}
